apiVersion: v1
kind: Service
metadata:
  name: warehouse-api
spec:
  selector:
    app: warehouse-api
  ports:
    - protocol: TCP
      port: 7065
      targetPort: 80
      nodePort: 30065
  type: NodePort